# Generated by Django 6.0.3 on 2026-03-24 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='machine',
            options={'verbose_name': 'Managed Machine', 'verbose_name_plural': 'Managed Machines'},
        ),
    ]
