# Generated by Django 6.0.3 on 2026-03-24 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0003_client_machine_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='cpu_model',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='machine',
            name='queued_file',
            field=models.FileField(blank=True, null=True, upload_to='deployments/'),
        ),
        migrations.AddField(
            model_name='machine',
            name='ram_gb',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
