# Generated by Django 6.0.3 on 2026-03-24 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0004_machine_cpu_model_machine_queued_file_machine_ram_gb'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='auto_maintenance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='machine',
            name='top_processes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
