# Generated by Django 6.0.3 on 2026-03-24 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0005_machine_auto_maintenance_machine_top_processes'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='disk_usage_percent',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
