# Generated by Django 6.0.3 on 2026-03-24 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0007_auditlog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='machine',
            options={},
        ),
        migrations.AddField(
            model_name='machine',
            name='remote_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='machine',
            name='remote_password',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
