# Generated by Django 6.0.3 on 2026-03-24 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0009_client_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='mac_address',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='machine',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='machine',
            name='model_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
