# Generated by Django 6.0.3 on 2026-03-24 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0010_machine_mac_address_machine_manufacturer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='last_boot_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
