# Generated by Django 6.0.3 on 2026-03-25 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0011_machine_last_boot_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditlog',
            options={'ordering': ['-timestamp']},
        ),
    ]
